#if !canImport(ObjectiveC)
import XCTest

extension DataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataTests = [
        ("testHexDataPerformance", testHexDataPerformance),
        ("testHexStringPerformance", testHexStringPerformance),
        ("testRandomData", testRandomData),
    ]
}

extension ProcessTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProcessTests = [
        ("testGetExecutableURL", testGetExecutableURL),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testStringExtensions", testStringExtensions),
    ]
}

extension URLTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLTest = [
        ("testURL_appendingPathComponents", testURL_appendingPathComponents),
        ("testURL_isSupported", testURL_isSupported),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DataTests.__allTests__DataTests),
        testCase(ProcessTests.__allTests__ProcessTests),
        testCase(StringTests.__allTests__StringTests),
        testCase(URLTest.__allTests__URLTest),
    ]
}
#endif
